# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-Pod
version:      0.25
version_from: lib/Apache2/Pod.pm
installdirs:  site
requires:
    Apache2::Const:                0
    Carp:                          0
    File::Find:                    0
    File::Spec:                    0
    Pod::Find:                     1.3
    Pod::Simple:                   3.01
    Pod::Simple::HTML:             0
    Pod::Simple::Text:             0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
